# Generated by Django 5.0.1 on 2026-01-09 17:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ex: CSS001, CSSDM', max_length=10, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSS',
                'verbose_name_plural': 'CSS',
                'db_table': 'css',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin_cgtsim', 'Administrateur CGTSIM'), ('user_css', 'Utilisateur CSS'), ('viewer', 'Observateur')], default='user_css', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('two_fa_secret', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('css', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='cgtsim.css')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeFonds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description générale')),
                ('document_justificatif', models.FileField(blank=True, null=True, upload_to='demandes/justificatifs/%Y/%m/')),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('versed', 'Fonds versés'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_revision', models.DateTimeField(blank=True, null=True)),
                ('notes_revision', models.TextField(blank=True)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='cgtsim.css')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('revise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_revisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de fonds',
                'verbose_name_plural': 'Demandes de fonds',
                'db_table': 'demandes_fonds',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_interet', models.DecimalField(decimal_places=3, help_text='Taux annuel en pourcentage (ex: 4.500)', max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('closed', 'Clôturée')], default='active', max_length=20)),
                ('interets_courus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intérêts cumulés à ce jour', max_digits=15)),
                ('derniere_maj_interets', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='cgtsim.css')),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avance_liee', to='cgtsim.demandefonds')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'db_table': 'avances',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeJour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_besoin', models.DateField(verbose_name='Date où les fonds doivent être disponibles')),
                ('montant_jour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15, verbose_name='Total du jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours', to='cgtsim.demandefonds')),
            ],
            options={
                'verbose_name': 'Jour de demande',
                'verbose_name_plural': 'Jours de demande',
                'db_table': 'demandes_jours',
                'ordering': ['date_besoin'],
            },
        ),
        migrations.CreateModel(
            name='DemandeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('categorie', models.CharField(choices=[('fonctionnement', 'Fonctionnement'), ('investissement', 'Investissement'), ('sqi', 'SQI'), ('ebi', 'EBI')], max_length=20, verbose_name='Catégorie')),
                ('type_paiement', models.CharField(choices=[('fournisseurs_dd', 'Fournisseurs Dépôt Direct'), ('fournisseurs_cheque', 'Fournisseurs Chèques'), ('salaires_dd', 'Salaires Dépôt Direct'), ('salaires_cheque', 'Salaires Chèques')], max_length=30, verbose_name='Type de paiement')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cgtsim.demandejour')),
            ],
            options={
                'verbose_name': 'Ligne de demande',
                'verbose_name_plural': 'Lignes de demande',
                'db_table': 'demandes_items',
                'ordering': ['ordre', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('avance', 'Avance'), ('subvention', 'Subvention'), ('interet', 'Intérêt')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Positif pour avances/intérêts, négatif pour subventions', max_digits=15)),
                ('date_transaction', models.DateField(verbose_name='Date de la transaction')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cgtsim.avance')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_creees', to=settings.AUTH_USER_MODEL)),
                ('css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cgtsim.css')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cgtsim.demandefonds')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date_transaction', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='demandefonds',
            index=models.Index(fields=['css', 'statut'], name='demandes_fo_css_id_4d4883_idx'),
        ),
        migrations.AddIndex(
            model_name='demandefonds',
            index=models.Index(fields=['reference'], name='demandes_fo_referen_224ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='demandejour',
            index=models.Index(fields=['demande', 'date_besoin'], name='demandes_jo_demande_1ebb98_idx'),
        ),
        migrations.AddIndex(
            model_name='demandejour',
            index=models.Index(fields=['date_besoin'], name='demandes_jo_date_be_2832fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandejour',
            unique_together={('demande', 'date_besoin')},
        ),
        migrations.AddIndex(
            model_name='demandeitem',
            index=models.Index(fields=['jour', 'ordre'], name='demandes_it_jour_id_d373cc_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeitem',
            index=models.Index(fields=['categorie'], name='demandes_it_categor_212f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['css', 'date_transaction'], name='transaction_css_id_c5543a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type_transaction'], name='transaction_type_tr_187789_idx'),
        ),
    ]
